const state={
  page:'home', query:'', topic:'all', source:'all', sourceQuery:'',
  xp:+localStorage.getItem('skm_xp')||0,
  seen:+localStorage.getItem('skm_seen')||0,
  mastered:+localStorage.getItem('skm_mastered')||0,
  streak:+localStorage.getItem('skm_streak')||0,
  daily:JSON.parse(localStorage.getItem('skm_daily')||'{}'),
  modal:null,
  selected:null
};
let kanji=[],manifest={},slots=[],source450Data=[],characterStories=[],memory450=[],learning={};
const $=s=>document.querySelector(s);
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const today=()=>new Date().toISOString().slice(0,10);

const TOPICS=[
 ['personal','👤','Personal Information'],['family','👨‍👩‍👧','Family'],['home','🏠','Home & Daily Life'],['time','🕐','Time & Dates'],
 ['food','🍱','Food & Drink'],['shopping','🛍️','Shopping & Money'],['transport','🚆','Transportation'],['places','📍','Places & Directions'],
 ['work','💼','Work & Jobs'],['health','🩺','Health & Medical'],['weather','☀️','Weather & Seasons'],['leisure','🎵','Leisure & Hobbies'],
 ['communication','💬','Communication & Requests'],['public','🏢','Public Services'],['travel','🧳','Travel & Accommodation']
];

const STORY={
 '利用':{title:'ප්‍රයෝජනයට ගන්නවා',story:'දිනපතා ජීවිතයේ තියෙන දෙයක් අතට අරගෙන “මේක ප්‍රයෝජනයට ගන්නවා” කියලා මතක තියාගන්න.',trigger:'利用 → භාවිතා කරනවා',visual:'🛠️'},
 '窓口':{title:'සේවා කවුළුව',story:'කවුළුවක් ළඟට ගිහින් සේවාවක් ඉල්ලන කවුළුවක් මවාගන්න. 窓 = කවුළුව, 口 = මුඛය/විවෘත ස්ථානය.',trigger:'窓口 → කවුළු කවුන්ටරය',visual:'🪟'},
 '外国':{title:'විදේශ රට',story:'ඔයාගේ රටෙන් පිටත තියෙන රටක් සිතියමකින් බලන දර්ශනයක් මවාගන්න.',trigger:'外国 → විදේශ රට',visual:'🌍'},
 '郵便局':{title:'තැපැල් කාර්යාලය',story:'ලිපියක් අරගෙන තැපැල් කාර්යාලයට යන දර්ශනයක් මවාගන්න.',trigger:'郵便局 → තැපැල් කාර්යාලය',visual:'📮'},
 '情報':{title:'තොරතුරු',story:'දුරකථනයේ හෝ පුවරුවක වැදගත් තොරතුරු පේන දර්ශනයක් මතක තියාගන්න.',trigger:'情報 → තොරතුරු',visual:'📰'},
 '近所':{title:'අසල්වැසි ප්‍රදේශය',story:'ගෙදරට ළඟම තියෙන අසල්වැසි ගෙවල් කිහිපයක් මවාගන්න.',trigger:'近所 → අසල්වැසි ප්‍රදේශය',visual:'🏘️'},
 '相談':{title:'සාකච්ඡා කර උපදෙස් ගන්නවා',story:'ප්‍රශ්නයක් තියෙනකොට විශ්වාස කරන කෙනෙක් එක්ක කතා කරලා උපදෙස් ගන්න දර්ශනයක් මතක තියාගන්න.',trigger:'相談 → උපදෙස් ගැන කතා කිරීම',visual:'🗣️'},
 '自動':{title:'ස්වයංක්‍රීය',story:'කෙනෙක් තල්ලු නොකරත් යන්ත්‍රයක් තමන්ම ක්‍රියා කරන දර්ශනයක් මවාගන්න.',trigger:'自動 → ස්වයංක්‍රීය',visual:'⚙️'},
 '質問':{title:'ප්‍රශ්නය',story:'අත උස්සලා ගුරුවරයාගෙන් ප්‍රශ්නයක් අහන දර්ශනයක් මතක තියාගන්න.',trigger:'質問 → ප්‍රශ්නය',visual:'❓'},
 '洗う':{title:'සෝදනවා',story:'අත් දෙක වතුරෙන් සෝදන දර්ශනයක් මවාගන්න.',trigger:'洗う → සෝදනවා',visual:'🫧'},
 '学生':{title:'ශිෂ්‍යයා',story:'පොත් බෑගයක් අරගෙන පාසලට යන ශිෂ්‍යයෙක් මවාගන්න.',trigger:'学生 → ශිෂ්‍යයා',visual:'🎒'},
 '仕事':{title:'රැකියාව / වැඩ',story:'උදේ වැඩට ගිහින් තමන්ගේ රාජකාරිය කරන දර්ශනයක් මවාගන්න.',trigger:'仕事 → රැකියාව / වැඩ',visual:'💼'},
 '学校':{title:'පාසල',story:'පංති කාමරයක්, ගුරුවරයෙක් සහ සිසුන් සිටින පාසල් දර්ශනයක් මතක තියාගන්න.',trigger:'学校 → පාසල',visual:'🏫'},
 '元気':{title:'සෞඛ්‍ය සම්පන්න / හොඳ තත්ත්වයේ',story:'උදේ නැගිටලා ශක්තියෙන් දවස ආරම්භ කරන කෙනෙක් මවාගන්න.',trigger:'元気 → සෞඛ්‍ය සම්පන්න',visual:'💪'},
 '生活':{title:'ජීවිතය / දෛනික ජීවිතය',story:'උදේ සිට රාත්‍රිය දක්වා දිනපතා කරන වැඩ එකම දිනයක දර්ශන මාලාවක් ලෙස මතක තියාගන්න.',trigger:'生活 → දෛනික ජීවිතය',visual:'🏠'},
 '忙しい':{title:'කාර්යබහුල',story:'එකවර වැඩ ගොඩක් තියෙන නිසා වේගයෙන් එහා මෙහා යන කෙනෙක් මවාගන්න.',trigger:'忙しい → කාර්යබහුල',visual:'🏃'},
 '去年':{title:'පසුගිය අවුරුද්ද',story:'දින දර්ශනයේ මේ අවුරුද්දෙන් එක පියවරක් පස්සට යන දර්ශනයක් මවාගන්න.',trigger:'去年 → පසුගිය අවුරුද්ද',visual:'📆'},
 '働く':{title:'වැඩ කරනවා',story:'තමන්ගේ රැකියාවේ වගකීමක් කරලා අවසන් කරන කෙනෙක් මවාගන්න.',trigger:'働く → වැඩ කරනවා',visual:'🔧'},
 '先週':{title:'පසුගිය සතිය',story:'කැලැන්ඩරයේ මේ සතියෙන් එක කොටසක් පස්සට යන දර්ශනයක් මතක තියාගන්න.',trigger:'先週 → පසුගිය සතිය',visual:'🗓️'},
 '作る':{title:'හදනවා / නිර්මාණය කරනවා',story:'අමුද්‍රව්‍ය අරගෙන දෙයක් හදන කෙනෙක් මවාගන්න.',trigger:'作る → හදනවා',visual:'🛠️'},
 '人':{title:'මිනිසා',story:'මිනිස් හැඩයම Kanji එකේ මූලික රූපය ලෙස මතක තියාගන්න.',trigger:'人 → මිනිසා',visual:'🧍'},
 '夕方':{title:'සවස',story:'ඉර බැස යන වෙලාවේ අහස වෙනස් වෙන දර්ශනයක් මවාගන්න.',trigger:'夕方 → සවස',visual:'🌇'},
 '一人':{title:'එක් පුද්ගලයෙක්',story:'කණ්ඩායමක් නැතුව එකම කෙනෙක් සිටින දර්ශනයක් මතක තියාගන්න.',trigger:'一人 → එක් පුද්ගලයෙක්',visual:'1️⃣'},
 '英語':{title:'ඉංග්‍රීසි භාෂාව',story:'භාෂා පන්තියක English වචන කියවන දර්ශනයක් මවාගන්න.',trigger:'英語 → ඉංග්‍රීසි භාෂාව',visual:'🔤'},
 '二人':{title:'පුද්ගලයන් දෙදෙනෙක්',story:'මිතුරන් දෙදෙනෙක් එකට සිටින දර්ශනයක් මතක තියාගන්න.',trigger:'二人 → දෙදෙනෙක්',visual:'👥'},
 '音楽':{title:'සංගීතය',story:'ගීතයක් අහන විට ශබ්දය සහ සතුට එකට මතක තියාගන්න.',trigger:'音楽 → සංගීතය',visual:'🎵'},
 '犬':{title:'බල්ලා',story:'බල්ලා දිවගෙන එන සරල දර්ශනයක් මවාගන්න.',trigger:'犬 → බල්ලා',visual:'🐕'},
 '習う':{title:'ඉගෙන ගන්නවා',story:'ගුරුවරයෙකුගෙන් අලුත් දෙයක් ඉගෙන ගන්නා දර්ශනයක් මතක තියාගන්න.',trigger:'習う → ඉගෙන ගන්නවා',visual:'📚'},
 '家族':{title:'පවුල',story:'එකම ගෙදර එකට සිටින පවුලක් මවාගන්න.',trigger:'家族 → පවුල',visual:'👨‍👩‍👧'},
 '話す':{title:'කතා කරනවා',story:'මිතුරෙකු සමඟ මුහුණට මුහුණ කතා කරන දර්ශනයක් මතක තියාගන්න.',trigger:'話す → කතා කරනවා',visual:'💬'}
};

function save(){localStorage.setItem('skm_xp',state.xp);localStorage.setItem('skm_seen',state.seen);localStorage.setItem('skm_mastered',state.mastered);localStorage.setItem('skm_streak',state.streak);localStorage.setItem('skm_daily',JSON.stringify(state.daily));}
function ensureDaily(){if(state.daily.date!==today())state.daily={date:today(),done:0,ids:[]};}
function dailyPct(){ensureDaily();return Math.min(100,(state.daily.done||0)/25*100)}

function source450Card(x){
  const r=x.structured_record; const m=memoryFor(x.id);
  const jp=m?.japanese||r?.kanji||`Source ${x.page}-${x.slot}`;
  const si=m?.sinhala||r?.sinhala||'';
  const label=si?`${jp} · ${si}`:jp;
  return `<button class="source450-card" data-source-detail="${x.id}">
    <div class="source450-image-wrap"><img src="${x.crop}" loading="lazy" alt="Original source page ${x.page} slot ${x.slot}"></div>
    <div class="source450-meta"><span class="source-tag">${m?.creative_explanation?'Creative + Source':'Original Source'}</span><b>${esc(label)}</b><small>Page ${x.page} · Slot ${x.slot}</small></div>
  </button>`;
}
function source450(){
  const q=(state.sourceQuery||'').toLowerCase();
  const shown=source450Data.filter(x=>{
    const r=x.structured_record;
    const hay=[x.id,String(x.page),String(x.slot),r?.kanji||'',r?.furigana||'',r?.romaji||'',r?.sinhala||''].join(' ').toLowerCase();
    return !q||hay.includes(q);
  });
  return `${header()}<main class="app"><section class="page-head"><span class="eyebrow">450 SOURCE CARDS</span><h1>All 450 Source Entries</h1><p>Every source slot from the original 450-page scan is preserved. Existing structured records remain untouched.</p></section>
  <div class="search-wrap"><span>⌕</span><input id="sourceSearch" class="search" placeholder="Search structured data / page / slot" value="${esc(state.sourceQuery||'')}"><button id="clearSourceSearch">×</button></div>
  <div class="integrity"><span>🔒</span><div><b>${shown.length} / ${source450Data.length} source entries visible</b><p>The original source image is the authority for every entry. No OCR text is used to overwrite source data.</p></div></div>
  <div class="source450-grid">${shown.map(source450Card).join('')}</div></main>${nav()}${sourceDetailModal()}`;
}
function sourceDetailModal(){
 const id=state.modal&&String(state.modal).startsWith('source:')?String(state.modal).slice(7):null; if(!id)return '';
 const x=source450Data.find(v=>v.id===id),m=memoryFor(id),r=x?.structured_record; if(!x)return '';
 const jp=m?.japanese||r?.kanji||'Source entry'; const fur=m?.furigana||r?.furigana||''; const rom=m?.romaji||r?.romaji||''; const si=m?.sinhala||r?.sinhala||'Original source visual'; const chars=m?.character_stories||[];
 return `<div class="modal-backdrop" data-close="1"><div class="modal-card source-modal" onclick="event.stopPropagation()"><button class="modal-close" data-close="1">×</button><div class="modal-label">${m?.creative_explanation?'CREATIVE SINHALA MEMORY + SOURCE':'SOURCE + MEMORY AID'}</div><img class="source-modal-image" src="${esc(x.crop)}" alt="Original source entry page ${x.page} slot ${x.slot}"><div class="source-modal-meta"><span class="source-tag">Page ${x.page} · Slot ${x.slot}</span><div class="kanji-detail">${esc(jp)}</div><div class="reading">${esc(fur)}</div><div class="romaji">${esc(rom)}</div><div class="meaning">${esc(si)}</div></div><div class="story-panel creative-panel"><div class="story-visual">🧠</div><b>💡 Creative Sinhala Explanation</b><p>${esc(m?.creative_explanation||m?.memory_story||'Creative explanation unavailable.')}</p><strong>🧠 ${esc(m?.memory_trigger||`${jp} → ${si}`)}</strong><small class="memory-note">මෙය learning mnemonic එකක්. Official etymology එකක් නොවේ.</small></div>${chars.length?`<div class="panel compact-panel"><div class="panel-title">🧩 Character memory clues</div>${chars.map(c=>`<div class="character-story-row"><b>${esc(c.kanji)}</b><div><small>${esc(c.anchor_word)}</small><p>${esc(c.sinhala_memory_story)}</p></div></div>`).join('')}</div>`:''}<button class="primary full" data-source-learn="${esc(x.id)}">✓ Mark reviewed +10 XP</button><button class="secondary full" data-flash450="${esc(x.id)}">🎴 Open flashcard</button></div></div>`;
}
function nav(){return `<nav class="bottom"><div class="bottom-in">${[['home','⌂','Home'],['library','漢','Library'],['daily','25','Daily'],['cards','🎴','Cards'],['more','☷','More']].map(([p,i,t])=>`<button class="nav-btn ${state.page===p?'active':''}" data-page="${p}"><span>${i}</span><small>${t}</small></button>`).join('')}</div></nav>`}
function header(){return `<header class="topbar"><div class="top-inner"><button class="icon-btn" data-page="home">☰</button><div><div class="appname">Sihina Kanji Master</div><div class="subtitle">Japanese • Furigana • Romaji • Sinhala</div></div><button class="profile">SL</button></div></header>`}
function statCard(icon,label,value,sub=''){return `<div class="stat-card"><div class="stat-icon">${icon}</div><div class="stat-label">${label}</div><div class="stat-value">${value}</div><div class="stat-sub">${sub}</div></div>`}
function menuTile(icon,title,sub,page,cls=''){return `<button class="menu-tile ${cls}" data-page="${page}"><span class="tile-icon">${icon}</span><span><b>${title}</b><small>${sub}</small></span><span class="arrow">›</span></button>`}
function home(){ensureDaily();const mastered=Math.min(100,Math.round((state.mastered/Math.max(1,kanji.length))*100));return `${header()}<main class="app">
<section class="hero-card"><div class="hero-orb">漢</div><div><span class="eyebrow">DAILY KANJI LAB</span><h1>Learn Kanji.<br><em>Remember for life.</em></h1><p>Source-preserving learning with Sinhala memory cues and JFT-useful word families.</p></div></section>
<section class="stats-grid">${statCard('🎯','Today',`${state.daily.done||0}/25`,'daily target')}${statCard('🔥','Streak',state.streak,'days')}${statCard('⚡','XP',state.xp,'learning points')}${statCard('🏆','Mastered',state.mastered,`${mastered}% of structured`)}</section>
<section class="section"><div class="section-head"><div><span class="eyebrow">TODAY</span><h2>Daily 25 Kanji</h2></div><button class="text-btn" data-page="daily">View all ›</button></div><div class="daily-card"><div class="progress-ring" style="--p:${dailyPct()}%"><div><strong>${state.daily.done||0}</strong><small>/25</small></div></div><div class="daily-copy"><b>Keep your streak alive 🔥</b><p>Recognition → reading → Sinhala cue → word family → recall.</p><button class="primary" data-page="daily">Continue practice</button></div></div></section>
<section class="section"><div class="section-head"><div><span class="eyebrow">QUICK LEARN</span><h2>Explore</h2></div></div><div class="menu-grid">${menuTile('📚','All Kanji','450 source entries','source450','purple')}${menuTile('🧠','Memory Stories','All 450 source entries','stories','teal')}${menuTile('🎴','Flashcards','Tap to reveal','cards','lime')}${menuTile('✍️','Writing Practice','Stroke reference + recall','writing','yellow')}${menuTile('🔊','Reading','Japanese pronunciation','reading','blue')}${menuTile('📝','Quiz','Japanese + Furigana','quiz','navy')}${menuTile('📈','Progress','Mastery + SRS','progress','coral')}${menuTile('🎮','Games','Fast recall challenges','games','mint')}</div></section>
<section class="section"><div class="section-head"><div><span class="eyebrow">JFT-ORIENTED</span><h2>Topics</h2></div><button class="text-btn" data-page="topics">All topics ›</button></div><div class="topic-row">${TOPICS.slice(0,8).map(t=>`<button class="topic-pill" data-topic="${t[0]}">${t[1]} ${t[2]}</button>`).join('')}</div></section>
<section class="section"><div class="section-head"><div><span class="eyebrow">SOURCE LIBRARY</span><h2>Original PDFs</h2></div></div><div class="source-grid"><button class="source-card" data-source="all450"><span>📘</span><b>Kanji all 450</b><small>47 pages • original scan</small></button><button class="source-card" data-source="n4"><span>📙</span><b>N4 Kanji</b><small>132 pages • original scan</small></button></div></section>
<section class="integrity"><span>🔒</span><div><b>Source data is frozen</b><p>Original JSON/PDF records are kept untouched. New stories, UI and learning helpers live in separate layers.</p></div></section>
</main>${nav()}${modal()}`}
function library(){let q=state.query.toLowerCase();let shown=kanji.filter(x=>[x.kanji,x.furigana,x.romaji,x.sinhala].join(' ').toLowerCase().includes(q));return `${header()}<main class="app"><section class="page-head"><span class="eyebrow">LIBRARY</span><h1>All source records</h1><p>Original structured records stay unchanged. Search and learn around them.</p></section><div class="search-wrap"><span>⌕</span><input id="search" class="search" placeholder="Japanese / Furigana / Romaji / Sinhala" value="${esc(state.query)}"><button id="clearSearch">×</button></div><div class="filter-row"><button class="filter active">Structured ${kanji.length}</button><button class="filter" data-page="source">All 450 source slots</button><button class="filter" data-page="topics">JFT topics</button></div><div class="grid">${shown.map(card).join('')}</div>${shown.length?'':'<div class="empty">No structured record matches. Open Source Pages to browse the original scans.</div>'}</main>${nav()}${modal()}`}
function card(x){const st=STORY[x.kanji]||{visual:'🈶',title:x.sinhala||'Learning cue',story:`${x.kanji} කියන වචනයේ අර්ථය ${x.sinhala||'source meaning'} ලෙස මතක තියාගන්න.`,trigger:`${x.kanji} → ${x.sinhala||'meaning'}`};return `<article class="kanji-card"><div class="card-top"><span class="source-tag">P.${x.sourcePage}</span><button class="mini-btn" data-flash="${x.id}">🎴</button></div><div class="visual-badge">${st.visual}</div><div class="kanji-big">${esc(x.kanji)}</div><div class="reading">${esc(x.furigana)}</div><div class="romaji">${esc(x.romaji)}</div><div class="meaning">${esc(x.sinhala)}</div><div class="cue-line">🧠 ${esc(st.trigger)}</div><button class="learn-btn" data-detail="${x.id}">Open learning unit <span>›</span></button></article>`}
function detail(id){const x=kanji.find(k=>k.id===id);if(!x)return library();const st=STORY[x.kanji]||{visual:'🈶',title:x.sinhala||'Learning cue',story:`${x.kanji} කියන වචනයේ ${x.sinhala||'අර්ථය'} කියන scene එකක් මතක තියාගන්න.`,trigger:`${x.kanji} → ${x.sinhala||'meaning'}`};const family=kanji.filter(k=>k.kanji.split('').some(ch=>x.kanji.includes(ch))).filter(k=>k.id!==x.id).slice(0,5);return `${header()}<main class="app"><button class="back-btn" data-page="library">‹ Library</button><section class="detail-hero"><div class="detail-visual">${st.visual}</div><div><span class="eyebrow">KANJI LEARNING UNIT</span><div class="kanji-detail">${esc(x.kanji)}</div><div class="reading detail-reading">${esc(x.furigana)}</div><div class="romaji">${esc(x.romaji)}</div><div class="meaning detail-meaning">${esc(x.sinhala)}</div></div><button class="floating-card" data-flash="${x.id}">🎴<small>Flashcard</small></button></section>
<section class="detail-grid"><div class="panel"><div class="panel-title">🧩 Visual Clue</div><div class="visual-clue"><div class="clue-icon">${st.visual}</div><div><b>${esc(st.title)}</b><p>මෙය <strong>memory aid</strong> එකක්. Official etymology එකක් ලෙස නොගන්න.</p></div></div></div><div class="panel story-panel"><div class="panel-title">💡 සිංහල මතක කතාව</div><p>${esc(st.story)}</p><div class="trigger">🧠 ${esc(st.trigger)}</div></div></section>
<section class="panel"><div class="panel-title">🇯🇵 JFT-useful source words</div><p class="panel-note">මෙහි මුලින්ම පෙන්වන්නේ source records වලින්ම Kanji/character එක share කරන words. මේවා official JFT question claims නොව learning examples.</p><div class="word-list">${family.length?family.map(w=>`<button class="word-row" data-detail="${w.id}"><span class="word-jp">${esc(w.kanji)}</span><span><b>${esc(w.furigana)}</b><small>${esc(w.romaji)} • ${esc(w.sinhala)}</small></span><span>›</span></button>`).join(''):`<div class="empty">No additional structured source word found for this character.</div>`}</div></section>
<section class="panel"><div class="panel-title">🔊 Japanese Reading</div><div class="audio-row"><button class="audio-btn" data-speak="${esc(x.furigana)}">▶</button><div><b>Native-style browser speech</b><small>${esc(x.furigana)} • Japanese</small></div></div></section>
<section class="panel"><div class="panel-title">✍️ Stroke & Recall</div><div class="stroke-card"><div class="stroke-kanji">${esc(x.kanji)}</div><div><b>Source visual reference</b><p>The original PDF illustration remains unchanged. Animation is intentionally removed from this redesign.</p><button class="secondary" data-sourcepage="${x.sourcePage}">Open source page ↗</button></div></div></section>
<section class="panel"><div class="panel-title">🎯 Recall</div><button class="primary full" data-mark="${x.id}">I know this +10 XP</button></section>
</main>${nav()}${modal()}`}
function daily(){ensureDaily();let items=[];for(let i=0;i<25;i++){let x=kanji[(state.daily.done+i)%kanji.length];if(x)items.push(x)}return `${header()}<main class="app"><section class="page-head"><span class="eyebrow">TODAY'S TARGET</span><h1>25 Kanji</h1><p>Repeat until recognition feels automatic.</p></section><div class="daily-banner"><div class="big-count">${state.daily.done||0}<small>/25</small></div><div><b>${Math.round(dailyPct())}% complete</b><div class="bar"><i style="width:${dailyPct()}%"></i></div><p>Each card: Japanese → reading → Sinhala cue → word family → recall.</p></div></div><div class="grid">${items.map(x=>`<article class="kanji-card compact"><div class="card-top"><span class="source-tag">Daily</span><button class="mini-btn" data-flash="${x.id}">🎴</button></div><div class="kanji-big">${esc(x.kanji)}</div><div class="reading">${esc(x.furigana)}</div><div class="romaji">${esc(x.romaji)}</div><div class="meaning">${esc(x.sinhala)}</div><button class="learn-btn" data-mark-daily="${x.id}">${state.daily.ids.includes(x.id)?'✓ Learned':'Mark learned'} <span>›</span></button></article>`).join('')}</div></main>${nav()}${modal()}`}
function cards(){const x=kanji[state.seen%Math.max(1,kanji.length)]||kanji[0];return `${header()}<main class="app"><section class="page-head"><span class="eyebrow">SMART FLASHCARDS</span><h1>Tap. Reveal. Recall.</h1><p>Flashcards open as a comfortable iOS-style popup, without leaving your study screen.</p></section><div class="flash-preview" data-flash="${x?.id||''}"><div class="flash-mark">🎴</div><div class="kanji-detail">${esc(x?.kanji||'漢')}</div><div class="reading">${esc(x?.furigana||'かんじ')}</div><div class="romaji">${esc(x?.romaji||'kanji')}</div><div class="hint">Tap to open card</div></div><div class="grid"><button class="panel action-tile" data-page="daily"><b>🎯 Daily 25</b><small>Targeted practice</small></button><button class="panel action-tile" data-page="quiz"><b>📝 Pure Japanese Quiz</b><small>Japanese + Furigana</small></button></div></main>${nav()}${modal()}`}
function stories(){return `${header()}<main class="app"><section class="page-head"><span class="eyebrow">450 MEMORY LAB</span><h1>Sinhala Kanji Stories</h1><p>All 450 original source entries are available here. Structured entries use their dedicated Sinhala story; every other entry keeps the original scan as the authoritative visual source.</p></section><div class="source450-grid">${source450Data.map(x=>{const r=x.structured_record;const st=r?STORY[r.kanji]:null;return `<button class="source450-card" data-source-detail="${x.id}"><div class="source450-image-wrap"><img src="${x.crop}" loading="lazy" alt="Original source page ${x.page} slot ${x.slot}"></div><div class="source450-meta"><span class="source-tag">${st?'Sinhala Story + Source':'Source + Memory Aid'}</span><b>${esc(st?.title||r?.kanji||`Source entry ${x.page}-${x.slot}`)}</b><small>Page ${x.page} · Slot ${x.slot}</small></div></button>`}).join('')}</div></main>${nav()}${sourceDetailModal()}`}
function topics(){return `${header()}<main class="app"><section class="page-head"><span class="eyebrow">JFT ORIENTED</span><h1>15 Topic Navigation</h1><p>Topic navigation is a UI layer. It does not rewrite source records.</p></section><div class="topic-grid">${TOPICS.map(t=>`<button class="topic-card" data-topic="${t[0]}"><span>${t[1]}</span><b>${t[2]}</b><small>Explore source-linked words</small><em>›</em></button>`).join('')}</div><section class="panel topic-results"><div class="panel-title">${state.topic==='all'?'Choose a topic':TOPICS.find(t=>t[0]===state.topic)?.[2]||'Topic'}</div><p>Current structured source records can be searched here. Topic labels are navigation helpers, not claims that a word is an official JFT item.</p><div class="chips">${kanji.slice(0,12).map(x=>`<button class="chip" data-detail="${x.id}">${esc(x.kanji)} · ${esc(x.sinhala)}</button>`).join('')}</div></section></main>${nav()}${modal()}`}
function progress(){const total=kanji.length;const pct=Math.round((state.mastered/Math.max(1,total))*100);return `${header()}<main class="app"><section class="page-head"><span class="eyebrow">MASTERY</span><h1>Your Kanji Progress</h1><p>Learning state is stored locally on this device.</p></section><div class="master-card"><div class="progress-ring large" style="--p:${pct}%"><div><strong>${pct}%</strong><small>mastery</small></div></div><div><b>${state.mastered} mastered</b><p>${state.seen} review actions • ${state.xp} XP • ${state.streak} day streak</p></div></div><div class="stats-grid">${statCard('👀','Seen',state.seen,'review actions')}${statCard('🏆','Mastered',state.mastered,'structured')}${statCard('⚡','XP',state.xp,'earned')}${statCard('🔥','Streak',state.streak,'days')}</div><section class="panel"><div class="panel-title">SRS buttons</div><div class="srs-grid"><button data-srs="again">Again</button><button data-srs="hard">Hard</button><button data-srs="good">Good</button><button data-srs="mastered">Mastered</button></div></section></main>${nav()}${modal()}`}
function writing(){return `${header()}<main class="app"><section class="page-head"><span class="eyebrow">WRITING</span><h1>Write & Recall</h1><p>Use the original source page as the visual reference. No fabricated animated stroke layer.</p></section><div class="writing-card"><div class="writing-kanji">漢</div><div class="writing-grid"><div>1<br><small>Observe source</small></div><div>2<br><small>Trace on paper</small></div><div>3<br><small>Write from memory</small></div><div>4<br><small>Recognize</small></div></div><button class="primary" data-page="daily">Practice today's 25</button></div></main>${nav()}${modal()}`}
function reading(){return `${header()}<main class="app"><section class="page-head"><span class="eyebrow">READING</span><h1>Japanese Reading Lab</h1><p>Normal learning mode keeps Japanese + Furigana + Romaji + Sinhala together.</p></section><div class="grid">${kanji.slice(0,12).map(x=>`<article class="panel reading-card"><div class="kanji-small">${esc(x.kanji)}</div><div class="reading">${esc(x.furigana)}</div><div class="romaji">${esc(x.romaji)}</div><div class="meaning">${esc(x.sinhala)}</div><button class="audio-btn wide" data-speak="${esc(x.furigana)}">▶ Listen Japanese</button></article>`).join('')}</div></main>${nav()}${modal()}`}
function quiz(){const x=kanji[state.seen%Math.max(1,kanji.length)]||kanji[0];const opts=[x.furigana,...kanji.filter(k=>k.id!==x.id).map(k=>k.furigana).filter(Boolean).slice(0,3)];return `${header()}<main class="app"><section class="page-head"><span class="eyebrow">EXAM MODE</span><h1>Pure Japanese Quiz</h1><p>Japanese + Furigana only. Romaji and Sinhala stay hidden.</p></section><div class="quiz-card"><div class="quiz-jp">${esc(x.kanji)}<small>${esc(x.furigana)}</small></div><div class="quiz-options">${opts.map((o,i)=>`<button class="quiz-option" data-quiz="${esc(o)}" data-correct="${i===0?'1':'0'}">${esc(o)}</button>`).join('')}</div></div></main>${nav()}${modal()}`}
function games(){return `${header()}<main class="app"><section class="page-head"><span class="eyebrow">KANJI GAMES</span><h1>Quick Recall Arcade</h1><p>Short sessions designed to reinforce the daily target.</p></section><div class="game-grid"><button class="game-card" data-page="quiz"><span>⚡</span><b>Speed Reading</b><small>Choose the reading</small></button><button class="game-card" data-page="cards"><span>🧠</span><b>Memory Match</b><small>Reveal and recall</small></button><button class="game-card" data-page="writing"><span>✍️</span><b>Stroke Recall</b><small>Write from memory</small></button><button class="game-card" data-page="daily"><span>🔥</span><b>25 Challenge</b><small>Finish today's target</small></button></div></main>${nav()}${modal()}`}
function more(){return `${header()}<main class="app"><section class="page-head"><span class="eyebrow">MENU</span><h1>All sections</h1></section><div class="menu-grid">${menuTile('📚','All Kanji','450 source entries','source450','purple')}${menuTile('🧠','Memory Stories','Sinhala cues','stories','teal')}${menuTile('🎯','Daily 25','Daily practice','daily','lime')}${menuTile('🎴','Flashcards','Popup cards','cards','yellow')}${menuTile('✍️','Writing','Recall','writing','blue')}${menuTile('🔊','Reading','Japanese audio','reading','navy')}${menuTile('📝','Quiz','Exam mode','quiz','coral')}${menuTile('🎮','Games','Recall arcade','games','mint')}${menuTile('📈','Progress','Mastery','progress','purple')}${menuTile('🗂️','JFT Topics','15 categories','topics','teal')}${menuTile('📄','Source Pages','450 + N4 scans','source','blue')}</div></main>${nav()}${modal()}`}
function source(){return `${header()}<main class="app"><section class="page-head"><span class="eyebrow">SOURCE VIEWER</span><h1>Original pages</h1><p>Every source slot remains accessible. Nothing is deleted or rewritten.</p></section><div class="source-grid">${Array.from({length:47},(_,i)=>i+1).map(p=>`<button class="source-card big" data-sourcepage="${p}"><img src="./assets/pages/all450-${String(p).padStart(2,'0')}.jpg"><b>Kanji all 450 · Page ${p}</b></button>`).join('')}</div><section class="panel"><div class="panel-title">N4 Kanji · 132 pages</div><button class="primary full" data-source="n4">Open original N4 PDF</button></section></main>${nav()}${modal()}`}
function modal(){if(!state.modal)return '';const x=kanji.find(k=>k.id===state.modal)||kanji[0];if(!x)return '';return `<div class="modal-backdrop" data-close="1"><div class="modal-card" onclick="event.stopPropagation()"><button class="modal-close" data-close="1">×</button><div class="modal-label">FLASHCARD</div><div class="modal-visual">${(STORY[x.kanji]||{visual:'🈶'}).visual}</div><div class="kanji-detail">${esc(x.kanji)}</div><div class="reading">${esc(x.furigana)}</div><div class="romaji">${esc(x.romaji)}</div><div class="meaning">${esc(x.sinhala)}</div><div class="modal-divider"></div><div class="tri"><span>🇯🇵 ${esc(x.kanji)}</span><span>あ ${esc(x.furigana)}</span><span>🔤 ${esc(x.romaji)}</span><span>🇱🇰 ${esc(x.sinhala)}</span></div><button class="primary full" data-mark="${x.id}" data-close-after="1">Again / Review +10 XP</button><button class="secondary full" data-detail="${x.id}" data-close-after="1">Open full learning unit</button></div></div>`}
// --- Sihina Kanji Master 450-source learning layer (additive; source data untouched) ---
function memoryFor(id){ return memory450.find(x=>x.source_entry_id===id) || null; }
function sourceRecordFor(id){ const x=source450Data.find(v=>v.id===id); return x?.structured_record || null; }
function sourceDetailModal(){
  const id=state.modal?.startsWith('source:')?state.modal.slice(7):null; if(!id)return '';
  const x=source450Data.find(v=>v.id===id); if(!x)return '';
  const m=memoryFor(id); const r=x.structured_record;
  const chars=m?.character_stories||[];
  return `<div class="modal-backdrop" data-close="1"><div class="modal-card source-modal" onclick="event.stopPropagation()"><button class="modal-close" data-close="1">×</button><div class="modal-label">${m?.story_status==='structured_source_memory_aid'?'KANJI MEMORY + SOURCE':'SOURCE + MEMORY AID'}</div><img class="source-modal-image" src="${esc(x.crop)}" alt="Original source entry page ${x.page} slot ${x.slot}"><div class="source-modal-meta"><span class="source-tag">Page ${x.page} · Slot ${x.slot}</span>${r?`<div class="kanji-detail">${esc(r.kanji)}</div><div class="reading">${esc(r.furigana)}</div><div class="romaji">${esc(r.romaji)}</div><div class="meaning">${esc(r.sinhala)}</div>`:`<div class="meaning">Original source visual</div>`}</div><div class="story-panel creative-panel"><div class="story-visual">🧠</div><b>💡 Creative Sinhala Explanation</b><p>${esc(m?.creative_explanation||m?.memory_story||'Creative explanation unavailable.')}</p><strong>🧠 ${esc(m?.memory_trigger||'Source → meaning → recall')}</strong><small class="memory-note">මෙය learning mnemonic එකක්. Official etymology එකක් නොවේ.</small></div>${chars.length?`<div class="panel compact-panel"><div class="panel-title">🧩 Character memory clues</div>${chars.map(c=>`<div class="character-story-row"><b>${esc(c.kanji)}</b><div><small>${esc(c.anchor_word)}</small><p>${esc(c.sinhala_memory_story)}</p></div></div>`).join('')}</div>`:''}<button class="primary full" data-source-learn="${esc(x.id)}">✓ Mark reviewed +10 XP</button><button class="secondary full" data-flash450="${esc(x.id)}">🎴 Open flashcard</button></div></div>`;
}
function library(){ const q=(state.query||'').toLowerCase(); const shown=source450Data.filter(x=>{const r=x.structured_record||{};const m=memoryFor(x.id)||{};return !q||[x.id,x.page,x.slot,r.kanji,r.furigana,r.romaji,r.sinhala,m.memory_trigger].join(' ').toLowerCase().includes(q)}); return `${header()}<main class="app"><section class="page-head"><span class="eyebrow">ALL 450 SOURCE ENTRIES</span><h1>All 450 Kanji Source Cards</h1><p>Every source entry is preserved. Structured text is shown only where it is already verified; original source images remain the authority.</p></section><div class="search-wrap"><span>⌕</span><input id="search" class="search" placeholder="Search Japanese / Furigana / Romaji / Sinhala / page" value="${esc(state.query)}"><button id="clearSearch">×</button></div><div class="integrity"><span>🔒</span><div><b>${shown.length} / ${source450Data.length} entries</b><p>No source record is rewritten or deleted.</p></div></div><div class="source450-grid">${shown.map(source450Card).join('')}</div></main>${nav()}${modal()}`; }
function daily(){ ensureDaily(); const items=[]; for(let i=0;i<25;i++){const x=source450Data[(state.daily.done+i)%Math.max(1,source450Data.length)]; if(x)items.push(x);} return `${header()}<main class="app"><section class="page-head"><span class="eyebrow">TODAY'S TARGET</span><h1>25 Kanji Source Cards</h1><p>Every daily card keeps the original source visual and opens a flashcard popup.</p></section><div class="daily-banner"><div class="big-count">${state.daily.done||0}<small>/25</small></div><div><b>${Math.round(dailyPct())}% complete</b><div class="bar"><i style="width:${dailyPct()}%"></i></div><p>Japanese → Furigana → Romaji → Sinhala → memory cue → recall.</p></div></div><div class="source450-grid">${items.map(x=>{const r=x.structured_record,m=memoryFor(x.id);const jp=m?.japanese||r?.kanji||'Source';const fur=m?.furigana||r?.furigana||'';const rom=m?.romaji||r?.romaji||'';const si=m?.sinhala||r?.sinhala||'Source visual';return `<article class="kanji-card compact"><div class="card-top"><span class="source-tag">Daily</span><button class="mini-btn" data-flash450="${x.id}">🎴</button></div><div class="source450-image-wrap"><img src="${x.crop}" loading="lazy" alt="Original source"></div><div class="kanji-big">${esc(jp)}</div><div class="reading">${esc(fur)}</div><div class="romaji">${esc(rom)}</div><div class="meaning">${esc(si)}</div><button class="learn-btn" data-mark-daily="${x.id}">${state.daily.ids.includes(x.id)?'✓ Learned':'Mark learned'} <span>›</span></button></article>`}).join('')}</div></main>${nav()}${modal()}`; }
function cards(){ const x=source450Data[state.seen%Math.max(1,source450Data.length)]||source450Data[0]; const r=x?.structured_record; return `${header()}<main class="app"><section class="page-head"><span class="eyebrow">450-SOURCE FLASHCARDS</span><h1>Tap. Reveal. Recall.</h1><p>All 450 source entries are available to the popup flashcard engine.</p></section><div class="flash-preview" data-flash450="${x?.id||''}"><div class="flash-mark">🎴</div>${r?`<div class="kanji-detail">${esc(r.kanji)}</div><div class="reading">${esc(r.furigana)}</div><div class="romaji">${esc(r.romaji)}</div><div class="meaning">${esc(r.sinhala)}</div>`:'<div class="kanji-detail">SOURCE</div><div class="hint">Original source card</div>'}<div class="hint">Tap to open card</div></div><div class="grid"><button class="panel action-tile" data-page="daily"><b>🎯 Daily 25</b><small>Targeted practice</small></button><button class="panel action-tile" data-page="stories"><b>🧠 450 Memory Lab</b><small>Source-preserving memory aids</small></button></div></main>${nav()}${modal()}`; }
function stories(){return `${header()}<main class="app"><section class="page-head"><span class="eyebrow">450 MEMORY LAB</span><h1>Sinhala Kanji Stories</h1><p>Every one of the 450 source entries has a dedicated memory-aid record. Existing source data remains unchanged.</p></section><div class="source450-grid">${source450Data.map(x=>{const r=x.structured_record,m=memoryFor(x.id);return `<button class="source450-card" data-source-detail="${x.id}"><div class="source450-image-wrap"><img src="${x.crop}" loading="lazy" alt="Original source page ${x.page} slot ${x.slot}"></div><div class="source450-meta"><span class="source-tag">${m?.story_status==='structured_source_memory_aid'?'Sinhala Story + Source':'Source Visual Memory Aid'}</span><b>${esc(r?.kanji||`Source ${x.page}-${x.slot}`)}</b><small>${esc(m?.memory_trigger||'Source visual → recall')}</small></div></button>`}).join('')}</div></main>${nav()}${sourceDetailModal()}`; }
function progress(){const total=source450Data.length||450;const pct=Math.round((state.mastered/Math.max(1,total))*100);return `${header()}<main class="app"><section class="page-head"><span class="eyebrow">MASTERY</span><h1>Your 450-Source Progress</h1><p>Progress is tracked locally without modifying source data.</p></section><div class="master-card"><div class="progress-ring large" style="--p:${pct}%"><div><strong>${pct}%</strong><small>mastery</small></div></div><div><b>${state.mastered} mastered</b><p>${state.seen} review actions • ${state.xp} XP • ${state.streak} day streak</p></div></div><div class="stats-grid">${statCard('👀','Seen',state.seen,'review actions')}${statCard('🏆','Mastered',state.mastered,`of ${total}`)}${statCard('⚡','XP',state.xp,'earned')}${statCard('🔥','Streak',state.streak,'days')}</div></main>${nav()}${modal()}`; }
function modal(){if(!state.modal)return ''; if(String(state.modal).startsWith('s450:')){const id=String(state.modal).slice(5),x=source450Data.find(v=>v.id===id),m=memoryFor(id),r=x?.structured_record;if(!x)return '';return `<div class="modal-backdrop" data-close="1"><div class="modal-card" onclick="event.stopPropagation()"><button class="modal-close" data-close="1">×</button><div class="modal-label">450 SOURCE FLASHCARD</div>${`<img class="source-modal-image" src="${x.crop}" alt="Original source"><div class="kanji-detail">${esc(m?.japanese||r?.kanji||'Source entry')}</div><div class="reading">${esc(m?.furigana||r?.furigana||'')}</div><div class="romaji">${esc(m?.romaji||r?.romaji||'')}</div><div class="meaning">${esc(m?.sinhala||r?.sinhala||'Source visual')}</div>`}<div class="modal-divider"></div><div class="story-panel creative-panel"><b>💡 Creative Sinhala Explanation</b><p>${esc(m?.creative_explanation||m?.memory_story||'Creative explanation unavailable.')}</p><strong>🧠 ${esc(m?.memory_trigger||'Source → meaning → recall')}</strong><small class="memory-note">මෙය learning mnemonic එකක්. Official etymology එකක් නොවේ.</small></div><button class="primary full" data-mark-source="${x.id}" data-close-after="1">Again / Review +10 XP</button></div></div>`} const x=kanji.find(k=>k.id===state.modal)||kanji[0];if(!x)return '';return `<div class="modal-backdrop" data-close="1"><div class="modal-card" onclick="event.stopPropagation()"><button class="modal-close" data-close="1">×</button><div class="modal-label">FLASHCARD</div><div class="modal-visual">${(STORY[x.kanji]||{visual:'🈶'}).visual}</div><div class="kanji-detail">${esc(x.kanji)}</div><div class="reading">${esc(x.furigana)}</div><div class="romaji">${esc(x.romaji)}</div><div class="meaning">${esc(x.sinhala)}</div><div class="modal-divider"></div><div class="tri"><span>🇯🇵 ${esc(x.kanji)}</span><span>あ ${esc(x.furigana)}</span><span>🔤 ${esc(x.romaji)}</span><span>🇱🇰 ${esc(x.sinhala)}</span></div><button class="primary full" data-mark="${x.id}" data-close-after="1">Again / Review +10 XP</button><button class="secondary full" data-detail="${x.id}" data-close-after="1">Open full learning unit</button></div></div>`}
function home(){ensureDaily();const total=source450Data.length||450;const mastered=Math.min(100,Math.round((state.mastered/Math.max(1,total))*100));return `${header()}<main class="app"><section class="hero-card"><div class="hero-orb">漢</div><div><span class="eyebrow">DAILY KANJI LAB</span><h1>Learn Kanji.<br><em>Remember for life.</em></h1><p>450-source learning with Sinhala memory cues and JFT-useful word families.</p></div></section><section class="stats-grid">${statCard('🎯','Today',`${state.daily.done||0}/25`,'daily target')}${statCard('🔥','Streak',state.streak,'days')}${statCard('⚡','XP',state.xp,'learning points')}${statCard('🏆','Mastered',state.mastered,`${mastered}% of 450`)}</section><section class="section"><div class="section-head"><div><span class="eyebrow">TODAY</span><h2>Daily 25</h2></div><button class="text-btn" data-page="daily">View all ›</button></div><div class="daily-card"><div class="progress-ring" style="--p:${dailyPct()}%"><div><strong>${state.daily.done||0}</strong><small>/25</small></div></div><div class="daily-copy"><b>Keep your streak alive 🔥</b><p>Recognition → reading → Sinhala cue → source-word recall.</p><button class="primary" data-page="daily">Continue practice</button></div></div></section><section class="section"><div class="section-head"><div><span class="eyebrow">QUICK LEARN</span><h2>Explore</h2></div></div><div class="menu-grid">${menuTile('📚','All 450','Every source entry','library','purple')}${menuTile('🧠','Memory Stories','450 memory-aid cards','stories','teal')}${menuTile('🎴','Flashcards','450 popup cards','cards','lime')}${menuTile('✍️','Writing Practice','Source reference + recall','writing','yellow')}${menuTile('🔊','Reading','Japanese pronunciation','reading','blue')}${menuTile('📝','Quiz','Japanese + Furigana','quiz','navy')}${menuTile('📈','Progress','450-source mastery','progress','coral')}${menuTile('🎮','Games','Fast recall challenges','games','mint')}</div></section><section class="section"><div class="section-head"><div><span class="eyebrow">JFT-ORIENTED</span><h2>Topics</h2></div><button class="text-btn" data-page="topics">All topics ›</button></div><div class="topic-row">${TOPICS.slice(0,8).map(t=>`<button class="topic-pill" data-topic="${t[0]}">${t[1]} ${t[2]}</button>`).join('')}</div></section><section class="integrity"><span>🔒</span><div><b>Source data is frozen</b><p>All 450 source entries and original PDFs remain preserved. Learning helpers are additive only.</p></div></section></main>${nav()}${modal()}`}

function render(){let h;switch(state.page){case'home':h=home();break;case'library':h=library();break;case'daily':h=daily();break;case'cards':h=cards();break;case'stories':h=stories();break;case'topics':h=topics();break;case'progress':h=progress();break;case'writing':h=writing();break;case'reading':h=reading();break;case'quiz':h=quiz();break;case'games':h=games();break;case'more':h=more();break;case'source':h=source();break;case'source450':h=source450();break;default:h=state.page.startsWith('detail:')?detail(state.page.split(':')[1]):home()}$('#app').innerHTML=h}

document.addEventListener('click',e=>{
 const close=e.target.closest('[data-close]');if(close){state.modal=null;render();return}
 const p=e.target.closest('[data-page]')?.dataset.page;if(p){state.page=p;state.modal=null;render();window.scrollTo(0,0);return}
 const sd=e.target.closest('[data-source-detail]')?.dataset.sourceDetail;if(sd){state.modal='source:'+sd;render();window.scrollTo(0,0);return}
 const sl=e.target.closest('[data-source-learn]')?.dataset.sourceLearn;if(sl){state.seen++;state.xp+=10;save();state.modal=null;render();return}
 const d=e.target.closest('[data-detail]')?.dataset.detail;if(d){state.page='detail:'+d;state.modal=null;render();window.scrollTo(0,0);return}
 const f=e.target.closest('[data-flash]')?.dataset.flash;if(f){state.modal=f;render();return}
 const md=e.target.closest('[data-mark-daily]')?.dataset.markDaily;if(md){ensureDaily();if(!state.daily.ids.includes(md)){state.daily.ids.push(md);state.daily.done=Math.min(25,state.daily.done+1);state.xp+=10;state.seen++;if(state.daily.done===25)state.streak++;save()}render();return}
 const m=e.target.closest('[data-mark]')?.dataset.mark;if(m){state.seen++;state.xp+=10;if(state.seen%10===0)state.mastered++;save();if(e.target.closest('[data-close-after]'))state.modal=null;render();return}
 const src=e.target.closest('[data-source]')?.dataset.source;if(src){window.open(src==='n4'?'./sources/n4-kanji.pdf':'./sources/kanji-all-450.pdf','_blank');return}
 const sp=e.target.closest('[data-sourcepage]')?.dataset.sourcepage;if(sp){window.open(`./sources/kanji-all-450.pdf#page=${sp}`,'_blank');return}
 const q=e.target.closest('[data-quiz]');if(q){state.xp+=q.dataset.correct==='1'?20:2;state.seen++;save();alert(q.dataset.correct==='1'?'正解！':'もう一度。');render();return}
 const topic=e.target.closest('[data-topic]')?.dataset.topic;if(topic){state.topic=topic;state.page='topics';render();return}
 const speak=e.target.closest('[data-speak]')?.dataset.speak;if(speak){const u=new SpeechSynthesisUtterance(speak);u.lang='ja-JP';speechSynthesis.cancel();speechSynthesis.speak(u);return}
 const clear=e.target.closest('#clearSearch');if(clear){state.query='';render();return}
 const clearSource=e.target.closest('#clearSourceSearch');if(clearSource){state.sourceQuery='';render();return}
});
document.addEventListener('input',e=>{if(e.target.id==='search'){state.query=e.target.value;render();const s=$('#search');if(s){s.focus();s.setSelectionRange(s.value.length,s.value.length)}} if(e.target.id==='sourceSearch'){state.sourceQuery=e.target.value;render();const s=$('#sourceSearch');if(s){s.focus();s.setSelectionRange(s.value.length,s.value.length)}}});
document.addEventListener('click',e=>{
 const f=e.target.closest('[data-flash450]')?.dataset.flash450;
 if(f){state.modal='s450:'+f;render();return;}
 const ms=e.target.closest('[data-mark-source]')?.dataset.markSource;
 if(ms){state.seen++;state.xp+=10;save();if(e.target.closest('[data-close-after]'))state.modal=null;render();return;}
});

async function load(){try{[kanji,manifest,slots,source450Data,characterStories,memory450]=await Promise.all([fetch('./data/kanji.json').then(r=>r.json()),fetch('./data/source-manifest.json').then(r=>r.json()),fetch('./data/source-slots.json').then(r=>r.json()),fetch('./data/source450-index.json').then(r=>r.json()),fetch('./data/kanji-character-stories.json').then(r=>r.json()),fetch('./data/kanji-memory-450.json').then(r=>r.json())]);}catch(err){console.error(err)}render()}
load();
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js');
